{
 "title": "API Server Troubleshooting",
 "description": "shancor charts",
 "tags": [ "shancor" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(apiserver_current_inflight_requests, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Client Request Rate (Current)",
   "type": "stat",
   "description": "Per second Request rate by error code",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(rest_client_requests_total{job=\"$job\",code=~\"2..\"}[1m]))",
     "legendFormat": "2xx per sec"
    },
    {
     "expr": "sum(irate(rest_client_requests_total{job=\"$job\",code=~\"4..\"}[1m]))",
     "legendFormat": "4xx per sec"
    },
    {
     "expr": "sum(irate(rest_client_requests_total{job=\"$job\",code=~\"5..\"}[1m]))",
     "legendFormat": "5xx per sec"
    }
   ]
  },
  {
   "title": "In Queue Requests",
   "type": "stat",
   "description": "Are requests \"backed up\" on the system? We want the lowest value possible.",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(instance)(increase(apiserver_current_inqueue_requests{job=\"$job\"}[2m]))",
     "legendFormat": "{{request_kind}}"
    }
   ]
  },
  {
   "title": "Top Resource Watches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, max by (kind)(max_over_time(apiserver_registered_watchers{job=\"$job\"}[2m])))",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Deprecated Api Usage Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, count_over_time(apiserver_requested_deprecated_apis{job=\"$job\"}[5m]))",
     "legendFormat": "{{resource}} - {{version}}"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(instance,host,method)(increase(rest_client_requests_total{job=\"$job\", code!~\"2..\"}[5m])) > 0",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Secret Cache Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apiserver_envelope_encryption_dek_cache_fill_percent{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Inflight Read Requests (Per Server)",
   "type": "timeseries",
   "description": "Per second number broken out per server, notice the irate. ",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(apiserver_current_inflight_requests{job=\"$job\", request_kind=\"readOnly\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Inflight Write Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(apiserver_current_inflight_requests{job=\"$job\",request_kind=\"mutating\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slowest API call",
   "type": "status-history",
   "description": " top 2 most latent API calls for that period. 60 seconds is the Timeout anything over 10 seconds should be investigated.  ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(2, histogram_quantile(0.90, max without(instance,scope,version, group,dry_run) (increase(apiserver_request_duration_seconds_bucket{job=\"$job\",subresource!=\"status\",subresource!=\"token\",subresource!=\"scale\",subresource!=\"/healthz\",subresource!=\"binding\",subresource!=\"proxy\",verb!=\"WATCH\"}[2m]))))",
     "legendFormat": "{{resource}}  {{verb}} "
    }
   ]
  },
  {
   "title": "API  Request Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "max(increase(apiserver_request_duration_seconds_bucket{job=\"$job\",subresource!=\"status\",subresource!=\"token\",subresource!=\"scale\",subresource!=\"/healthz\",subresource!=\"binding\",subresource!=\"proxy\",verb!=\"WATCH\"}[2m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Etcd Request Leg",
   "type": "heatmap",
   "description": "All Calls Heatmap to etcd server. Show etcd high level  if etcd is source of slowness",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "max by (le)(increase(etcd_request_duration_seconds_bucket{job=\"$job\"}[2m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Advanced", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Top Watch Events",
   "type": "stat",
   "description": "useful to understand the CPU usage of the kube-apiserver process",
   "gridPos": { "h": 17, "w": 4, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum without(instance)(increase(apiserver_watch_events_total{job=\"$job\"}[2m])))",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Workqueues Backlog",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, max without (instance)(workqueue_depth{job=\"$job\"}))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Duration Heatmap",
   "type": "heatmap",
   "description": "Red value shows heavy bucket spread",
   "gridPos": { "h": 15, "w": 16, "x": 8, "y": 42 },
   "targets": [
    {
     "expr": "max without(instance,name)(increase(workqueue_queue_duration_seconds_bucket{job=\"$job\"}[2m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Max Go Threads",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(go_threads{job=\"$job\"}[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Filter Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 57 },
   "targets": [
    {
     "expr": "max without(instance, filter)(increase(apiserver_request_filter_duration_seconds_bucket{job=\"$job\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Inflight Write Requests - 1m",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(irate(apiserver_current_inflight_requests{job=\"$job\",request_kind=\"mutating\"}[1m])) * 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Inflight Read Requests - 1m",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(irate(apiserver_current_inflight_requests{job=\"$job\", request_kind=\"readOnly\"}[1m])) * 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pressure Stall Info",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max without (instance)((irate(node_pressure_cpu_waiting_seconds_total{job=\"node-exporter\"}[1m])) * 100 and on(instance) (up{job=\"$job\"}))",
     "legendFormat": "Waiting"
    },
    {
     "expr": "max without (instance)((irate(node_pressure_io_waiting_seconds_total{job=\"node-exporter\"}[1m])) * 100 and on(instance) (up{job=\"$job\"}))",
     "legendFormat": "IO Waiting"
    },
    {
     "expr": "max without (instance)((irate(node_pressure_io_stalled_seconds_total{job=\"node-exporter\"}[1m])) * 100 and on(instance) (up{job=\"$job\"}))",
     "legendFormat": "IO Stalled"
    },
    {
     "expr": "max without (instance)((irate(node_pressure_memory_waiting_seconds_total{job=\"node-exporter\"}[1m])) * 100 and on(instance) (up{job=\"$job\"}))",
     "legendFormat": "Memory Waiting"
    },
    {
     "expr": "max without (instance)((irate(node_pressure_memory_stalled_seconds_total{job=\"node-exporter\"}[1m])) * 100 and on(instance) (up{job=\"$job\"}))",
     "legendFormat": "Memory Stalled"
    }
   ]
  }
 ]
}