{
 "title": "API Server V2 - Flow Control",
 "description": "shancor charts",
 "tags": [ "shancor" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "2m",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(apiserver_current_inflight_requests, job)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Request Terminations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_terminations_total{job=\"$job\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Secret Cache Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apiserver_envelope_encryption_dek_cache_fill_percent{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Resource Watches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, max by (kind)(apiserver_registered_watchers{job=\"$job\"}))",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Aggregator Unavailable Apiservice",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance)(aggregator_unavailable_apiservice{job=\"$job\"}) > 0.9",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "API Flow Control - Request in Use %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (max by (priority_level) (apiserver_flowcontrol_request_concurrency_in_use{}) / max by (priority_level) (apiserver_flowcontrol_request_concurrency_limit{}))",
     "legendFormat": "{{priority_level}}"
    }
   ]
  },
  {
   "title": "API  Request Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "max(increase(apiserver_request_duration_seconds_bucket{job=\"$job\",subresource!=\"status\",subresource!=\"token\",subresource!=\"scale\",subresource!=\"/healthz\",subresource!=\"binding\",subresource!=\"proxy\",verb!=\"WATCH\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Etcd Request Leg",
   "type": "heatmap",
   "description": "All Calls Heatmap to etcd server. Show etcd high level  if etcd is source of slowness",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "max by (le)(increase(etcd_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Slowest API call",
   "type": "status-history",
   "description": " top 2 most latent API calls for that period. 60 seconds is the Timeout anything over 10 seconds should be investigated.  ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(1, histogram_quantile(0.90, max without(instance,scope,version, group,dry_run) (rate(apiserver_request_duration_seconds_bucket{job=\"$job\",subresource!=\"status\",subresource!=\"token\",subresource!=\"scale\",subresource!=\"/healthz\",subresource!=\"binding\",subresource!=\"proxy\",verb!=\"WATCH\"}[$__rate_interval]))))",
     "legendFormat": "{{resource}}  {{verb}} "
    }
   ]
  },
  {
   "title": "Client Request Rate - 2m",
   "type": "timeseries",
   "description": "Request rate by error code",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(rest_client_requests_total{job=\"$job\",code=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} 2xx"
    },
    {
     "expr": "sum by (instance)(rate(rest_client_requests_total{job=\"$job\",code=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} 4xx"
    },
    {
     "expr": "sum by (instance)(rate(rest_client_requests_total{job=\"$job\",code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} 5xx"
    }
   ]
  },
  {
   "title": "p90 Request Wait Duration",
   "type": "timeseries",
   "description": "long requests spent queued",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, max without (instance) (increase(apiserver_flowcontrol_request_wait_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "{{flow_schema}}"
    }
   ]
  },
  {
   "title": "P90 How Long Requests Took to Execute",
   "type": "timeseries",
   "description": "long requests spent queued",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, max without (instance) (increase(apiserver_flowcontrol_request_execution_seconds_bucket{job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "{{flow_schema}}"
    }
   ]
  },
  {
   "title": "Admission Webhook Admission Duration",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(3, histogram_quantile(0.90, sum without(instance,type,operation) (increase(apiserver_admission_webhook_admission_duration_seconds_bucket{job=\"$job\"}[$__rate_interval]))))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Inqueue Requests",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "max without(instance)(apiserver_flowcontrol_current_inqueue_requests{})",
     "legendFormat": "{{instance}} - {{flow_schema}}"
    }
   ]
  },
  {
   "title": "executing requests ",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without (instance,endpoint,namespace,service) (apiserver_flowcontrol_current_executing_requests{job=\"$job\"})",
     "legendFormat": "{{flow_schema}}"
    }
   ]
  },
  {
   "title": "Deprecated Api Usage Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, apiserver_requested_deprecated_apis{job=\"$job\"})",
     "legendFormat": "{{resource}} - {{version}}"
    }
   ]
  },
  {
   "title": "Advanced",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 },
   "collapsed": true,
   "panels": [
    {
     "title": "Work Queue Duration Heatmap",
     "type": "heatmap",
     "description": "Red value shows heavy bucket spread",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 116 },
     "targets": [
      {
       "expr": "max without(instance,name)(increase(workqueue_queue_duration_seconds_bucket{job=\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Max Go Threads",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 131 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "go_threads{job=\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}