{
 "title": "EKS Controller Manager",
 "tags": [ "RiskyAdventure" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Top 5 View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Length of Time in Queue (Top 5)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, rate(workqueue_queue_duration_seconds_sum{job=\"$job\"}[5m]) / rate(workqueue_queue_duration_seconds_count{job=\"$job\"}[5m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "How Long Requests are Taking to Execute (Top 5)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, rate(workqueue_work_duration_seconds_sum{job=\"$job\"}[5m]) / rate(workqueue_work_duration_seconds_count{job=\"$job\"}[5m])) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Number of Objects Waiting to be Processed (Top 5)",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, sum_over_time(workqueue_depth{job=\"$job\"}[5m])) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Full View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Length of Time in Queue",
   "type": "timeseries",
   "description": "Length of Time in Queue",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(workqueue_queue_duration_seconds_sum{job=\"$job\"}[5m]) / rate(workqueue_queue_duration_seconds_count{job=\"$job\"}[5m]) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth (all)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum_over_time(workqueue_depth{job=\"$job\"}[5m]) > 1 ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"$job\"}[5m]) > 1) by (name)",
     "legendFormat": "{{cluster}} {{instance}} {{name}}"
    }
   ]
  }
 ]
}