{
 "title": "Node Troubleshooter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(kubelet_node_name, instance)"
    }
   },
   {
    "name": "kubelet_job",
    "label": "kubelet",
    "query": {
     "query": "label_values(kubelet_node_name,  job)"
    }
   },
   {
    "name": "node_exporter_job",
    "label": "node_exporter",
    "query": {
     "query": "label_values(node_cpu_seconds_total,  job)"
    }
   },
   {
    "name": "cadvisor_job",
    "label": "cadvisor",
    "query": {
     "query": "label_values(container_threads, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pods running",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_running_pods{instance=~\"$instance:\\\\d+\"}",
     "legendFormat": "{{node_kubernetes_io_instance_type}}"
    }
   ]
  },
  {
   "title": "Kubelet Inflight Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max_over_time(kubelet_http_inflight_requests{job=\"$kubelet_job\", instance=~\"$instance:\\\\d+\", path=\"metrics\"}[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Kubelet Resident Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$kubelet_job\", instance=~\"$instance:\\\\d+\"}",
     "legendFormat": "Kubelet memory"
    }
   ]
  },
  {
   "title": "Current Container Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_running_containers{job=\"$kubelet_job\", instance=~\"$instance:\\\\d+\"}",
     "legendFormat": "{{container_state}}"
    }
   ]
  },
  {
   "title": "Started Containers Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(kubelet_started_containers_errors_total{instance=~\"$instance:\\\\d+\"}[2m])",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Kubelet Discard Events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(kubelet_pleg_discard_events{instance=~\"$instance:\\\\d+\"}[2m])",
     "legendFormat": "Discard Events"
    }
   ]
  },
  {
   "title": "Runtime Operations Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(kubelet_runtime_operations_errors_total{instance=~\"$instance:\\\\d+\"}[2m])",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Storage Operation Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(storage_operation_errors_total{instance=~\"$instance:\\\\d+\"}[2m])",
     "legendFormat": "{{volume_plugin}}"
    }
   ]
  },
  {
   "title": "Started Pods Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(kubelet_started_pods_errors_total{instance=~\"$instance:\\\\d+\"}[2m])",
     "legendFormat": "Started Pod Errors"
    }
   ]
  },
  {
   "title": "Pod Sandbox Errors",
   "type": "stat",
   "description": "CNI issues quick look",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(kubelet_run_podsandbox_errors_total[2m]) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Per Core Current Utilization - 1 Minute Average",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (irate(node_cpu_seconds_total{instance=~\"$instance:\\\\d+\",mode=\"idle\"}[1m])) * 100",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "Per Core - One Minute Heat Map",
   "type": "status-history",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (irate(node_cpu_seconds_total{instance=~\"$instance:\\\\d+\",mode=\"idle\"}[1m])) * 100",
     "legendFormat": "core {{cpu}}"
    }
   ]
  },
  {
   "title": "Throttled Periods  (Bad Pods Limits)",
   "type": "stat",
   "description": "Need to change CFS limits",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3,max without(id,container,name,namespace, image)(increase(container_cpu_cfs_throttled_periods_total{job=\"$cadvisor_job\", instance=~\"$instance:\\\\d+\"}[5m])) /max without(id,container,name,namespace,image)(increase(container_cpu_cfs_periods_total{job=\"$cadvisor_job\", instance=~\"$instance:\\\\d+\"}[5m])))",
     "legendFormat": " pod {{pod}}"
    }
   ]
  },
  {
   "title": "Container % of Limits",
   "type": "stat",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max by(pod,container,instance)(irate(container_cpu_usage_seconds_total{image!=\"\", container!=\"\", instance=~\"$instance:\\\\d+\"}[1m])) / (max by (pod,container,instance)(container_spec_cpu_quota{image!=\"\", container!=\"\", instance=~\"$instance:\\\\d+\"}) / 100000))",
     "legendFormat": "{{pod}}{{container}}"
    }
   ]
  },
  {
   "title": "Throttle Process Seconds (CPU Seconds Throttled)",
   "type": "stat",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, (irate(container_cpu_cfs_throttled_seconds_total{instance=\"$instance\",job=\"cadvisor\"}[1m]))) > 0.5",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kubelet pod start duration seconds",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "increase(kubelet_pod_start_duration_seconds_bucket{instance=~\"$instance:\\\\d+\"}[2m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Run Podsandbox Duration",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 44 },
   "targets": [
    {
     "expr": "increase(kubelet_run_podsandbox_duration_seconds_bucket{instance=~\"$instance:\\\\d+\"}[2m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Pleg Relist Duration",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 44 },
   "targets": [
    {
     "expr": "increase(kubelet_pleg_relist_duration_seconds_bucket{instance=~\"$instance:\\\\d+\"}[2m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CPU Shares Ratio",
   "type": "bargauge",
   "description": "How system will act under load",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance, container)(container_spec_cpu_shares{job=\"$cadvisor_job\", container!=\"\", instance=~\"$instance:\\\\d+\"}) / ignoring(container) group_left sum by (instance)(container_spec_cpu_shares{job=\"$cadvisor_job\", container!=\"\", instance=~\"$instance:\\\\d+\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU Waiting in Seconds",
   "type": "timeseries",
   "description": "more processes to be run than CPU time available to handle them",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_schedstat_waiting_seconds_total{job=\"$node_exporter_job\", instance=~\"$instance:\\\\d+\"}[1m]) ",
     "legendFormat": "Cpu - {{cpu}}"
    }
   ]
  },
  {
   "title": "Pod Worker Duration",
   "type": "state-timeline",
   "description": "Duration in seconds to sync a single pod",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, histogram_quantile(0.90, increase(kubelet_pod_worker_duration_seconds_bucket{instance=~\"$instance:\\\\d+\"}[2m])))",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  { "title": "Advanced", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Pressure Stall Info",
   "type": "timeseries",
   "description": "PSI flag must be enabled. See https://facebookmicrosites.github.io/psi/docs/overview for details",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(irate(node_pressure_cpu_waiting_seconds_total{job=\"$node_exporter_job\", instance=~\"$instance:\\\\d+\"}[1m])) * 100",
     "legendFormat": "Some Threads Stalled"
    },
    {
     "expr": "(irate(node_pressure_io_waiting_seconds_total{instance=~\"$instance:\\\\d+\"}[1m])) * 100",
     "legendFormat": "Some Threads IO Waiting"
    },
    {
     "expr": "(irate(node_pressure_io_stalled_seconds_total{instance=~\"$instance:\\\\d+\"}[1m])) * 100",
     "legendFormat": "All Threads IO Stalled"
    },
    {
     "expr": "(irate(node_pressure_memory_waiting_seconds_total{instance=~\"$instance:\\\\d+\"}[1m])) * 100",
     "legendFormat": "Some Threads Memory Waiting"
    },
    {
     "expr": "(irate(node_pressure_memory_stalled_seconds_total{instance=~\"$instance:\\\\d+\"}[1m])) * 100",
     "legendFormat": "Some Threads Memory Stalled"
    }
   ]
  },
  {
   "title": "CSI Operations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "max without(method_name, migrated,grpc_status_code)(increase(csi_operations_seconds_bucket{job=\"$kubelet_job\",instance=~\"$instance:\\\\d+\"}[2m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Http Requests Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "increase(kubelet_http_requests_duration_seconds_bucket{instance=~\"$instance:\\\\d+\", path=\"metrics\"}[2m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "AWS API Request latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "increase(cloudprovider_aws_api_request_duration_seconds_bucket{job=\"$kubelet_job\", instance=~\"$instance:\\\\d+\"}[2m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Max Go Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(go_threads{job=\"$kubelet_job\",instance=~\"$instance:\\\\d+\"}[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Goroutines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(go_goroutines{job=\"$kubelet_job\",instance=~\"$instance:\\\\d+\"}[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}